export const ErrorCode = {
  AUDIO_UNSUPPORTED_TYPE: 'AUDIO_UNSUPPORTED_TYPE',
  AUDIO_TOO_LARGE: 'AUDIO_TOO_LARGE',
  NOTE_DUPLICATE_CLIENT_ID: 'NOTE_DUPLICATE_CLIENT_ID',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  CANDIDATE_FACT_NOT_FOUND: 'CANDIDATE_FACT_NOT_FOUND',
  ALREADY_REVIEWED: 'ALREADY_REVIEWED',
  FORBIDDEN: 'FORBIDDEN',
  MISSING_FIELD: 'MISSING_FIELD',
  INVALID_FIELD: 'INVALID_FIELD',
  QUEUE_ITEM_NOT_FOUND: 'QUEUE_ITEM_NOT_FOUND',
  QUEUE_ITEM_ALREADY_DECIDED: 'QUEUE_ITEM_ALREADY_DECIDED',
  QUEUE_ITEM_CONFIRM_NOT_ALLOWED: 'QUEUE_ITEM_CONFIRM_NOT_ALLOWED',
  MEMORY_ITEM_NOT_FOUND: 'MEMORY_ITEM_NOT_FOUND',
  BUDGET_CATEGORY_NOT_FOUND: 'BUDGET_CATEGORY_NOT_FOUND',
  BUDGET_CATEGORY_ARCHIVED: 'BUDGET_CATEGORY_ARCHIVED',
  PHOTO_UNSUPPORTED_TYPE: 'PHOTO_UNSUPPORTED_TYPE',
  PHOTO_TOO_LARGE: 'PHOTO_TOO_LARGE',
  PHOTO_NOT_FOUND: 'PHOTO_NOT_FOUND',
  PHOTO_LINK_TARGET_NOT_FOUND: 'PHOTO_LINK_TARGET_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

export interface ApiError {
  code: ErrorCode
  message: string
}
