export const ErrorCode = {
  AUDIO_UNSUPPORTED_TYPE: 'AUDIO_UNSUPPORTED_TYPE',
  AUDIO_TOO_LARGE: 'AUDIO_TOO_LARGE',
  NOTE_DUPLICATE_CLIENT_ID: 'NOTE_DUPLICATE_CLIENT_ID',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  CANDIDATE_FACT_NOT_FOUND: 'CANDIDATE_FACT_NOT_FOUND',
  ALREADY_REVIEWED: 'ALREADY_REVIEWED',
  FORBIDDEN: 'FORBIDDEN',
  MISSING_FIELD: 'MISSING_FIELD',
  TIDY_UP_NOT_FOUND: 'TIDY_UP_NOT_FOUND',
  TIDY_UP_ITEM_NOT_FOUND: 'TIDY_UP_ITEM_NOT_FOUND',
  TIDY_UP_ITEM_ALREADY_DECIDED: 'TIDY_UP_ITEM_ALREADY_DECIDED',
  CONTRADICTION_CONFIRM_NOT_ALLOWED: 'CONTRADICTION_CONFIRM_NOT_ALLOWED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

export interface ApiError {
  code: ErrorCode
  message: string
}
